name: Deploy to EC2

on:
  push:
    branches:
      - main  # Despliega solo cuando se hace push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H <IP_DE_TU_INSTANCIA> >> ~/.ssh/known_hosts

      - name: Deploy application to EC2
        run: |
          ssh ec2-user@54.164.144.74 << 'EOF'
            cd /var/www/mi-aplicacion || exit
            git pull origin main
            npm install
            pm2 restart all || pm2 start index.js --name "mi-aplicacion"
          EOF
