name: Deploy GitHub repo to AWS

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # AWS CLI Configuration
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
    
      # SSH Permissions
      - name: Set SSH key permissions
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

      # Copy repo files to the EC2 instance
      - name: Deploy to EC2
        run: |
          echo "Deploying application..."
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ec2-user@52.67.14.225 << 'EOF'
            sudo yum update -y
            sudo yum install -y git nodejs
            git clone https://github.com/esedgarcia/a-deploy.git
            cd a-deploy
            npm install
            npm start
          EOF
