name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Debes almacenar la clave privada SSH en los secretos de GitHub

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i "C:/Users/AlEgA/.ssh" ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Verificar si el directorio de la aplicación existe, si no, clonar el repositorio
          if [ ! -d "/home/ec2-user/mi-aplicacion" ]; then
            echo "Clonando repositorio..."
            git clone 
