name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # We use the secret with the loaded private key

    - name: Deploy to EC2
      run: |
        # Create the .ssh directory if it does not exist
        mkdir -p ~/.ssh
        
        # Save the private key in the file spidey.pem
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/spidey.pem
        
        # Setting the correct permissions for the private key
        chmod 600 ~/.ssh/spidey.pem

        # Connect to the EC2 server
        ssh -o StrictHostKeyChecking=no -i "~/.ssh/spidey.pem" ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Check if the application directory exists, if not, clone the repository.
          if [ ! -d "/home/ec2-user/mi-aplicacion" ]; then
            echo "Cloning repository..."
            git clone git@github.com:Alejandro2914/AWS-Spiderman.git /home/ec2-user/mi-aplicacion
          fi

          # Change to the application directory
          cd /home/ec2-user/mi-aplicacion

          # Get the latest changes from the repository
          git pull origin main

          # Install application dependencies
          npm install

          # Install PM2 if not already installed
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

          # Restart the application using PM2
          pm2 restart all || pm2 start npm --name "mi-aplicacion" -- start
        EOF

