name: Deploy to EC2

on:
  push:
    branches:
      - main  # Ajusta esto si usas una rama diferente

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Este paso obtiene tu código fuente desde el repositorio

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Especifica la versión de Node.js que necesites

    - name: Install dependencies
      run: |
        npm install  # Instala las dependencias de tu aplicación

    - name: Set up SSH and deploy to EC2
      run: |
        # Guardar la clave privada en un archivo temporal
        echo "${{ secrets.EC2_SSH_KEY }}" > private-key.pem
        chmod 600 private-key.pem  # Asegura que la clave tenga los permisos correctos
        
        # Conectarse a EC2 y realizar el despliegue
        ssh -o StrictHostKeyChecking=no -i private-key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /home/ec2-user/mi-aplicacion  # Cambia a la carpeta de tu app en EC2
          git pull origin main  # Hace pull de la rama principal
          npm install  # Instala las dependencias de la app
          npm run build  # Ejecuta el build si es necesario
          pm2 restart all  # Reinicia la app si usas pm2 para manejar el proceso
        EOF
